services:
  app_chinook:
    build:
      context: .
      dockerfile: .hasura-connector/Dockerfile.chinook
    environment:
      CONNECTION_URI: $APP_CHINOOK_CONNECTION_URI
      HASURA_SERVICE_TOKEN_SECRET: $APP_CHINOOK_HASURA_SERVICE_TOKEN_SECRET
      OTEL_EXPORTER_OTLP_ENDPOINT: $APP_CHINOOK_OTEL_EXPORTER_OTLP_ENDPOINT
      OTEL_SERVICE_NAME: $APP_CHINOOK_OTEL_SERVICE_NAME
    extra_hosts:
      - local.hasura.dev:host-gateway
    ports:
      - 7998:8080
