services:
  data_quality_mdata:
    build:
      context: .
      dockerfile: .hasura-connector/Dockerfile.mdata
    environment:
      CONNECTION_URI: $DATA_QUALITY_MDATA_CONNECTION_URI
      HASURA_SERVICE_TOKEN_SECRET: $DATA_QUALITY_MDATA_HASURA_SERVICE_TOKEN_SECRET
      OTEL_EXPORTER_OTLP_ENDPOINT: $DATA_QUALITY_MDATA_OTEL_EXPORTER_OTLP_ENDPOINT
      OTEL_SERVICE_NAME: $DATA_QUALITY_MDATA_OTEL_SERVICE_NAME
    extra_hosts:
      - local.hasura.dev:host-gateway
    ports:
      - 5427:8080
