services:
  app_datamanagement:
    build:
      context: .
      dockerfile: .hasura-connector/Dockerfile.datamanagement
    environment:
      CONNECTION_URI: $APP_DATAMANAGEMENT_CONNECTION_URI
      HASURA_SERVICE_TOKEN_SECRET: $APP_DATAMANAGEMENT_HASURA_SERVICE_TOKEN_SECRET
      OTEL_EXPORTER_OTLP_ENDPOINT: $APP_DATAMANAGEMENT_OTEL_EXPORTER_OTLP_ENDPOINT
      OTEL_SERVICE_NAME: $APP_DATAMANAGEMENT_OTEL_SERVICE_NAME
    extra_hosts:
      - local.hasura.dev:host-gateway
    ports:
      - 9515:8080
