services:
  data_quality_mdatax:
    build:
      context: .
      dockerfile: .hasura-connector/Dockerfile
    environment:
      HASURA_SERVICE_TOKEN_SECRET: $DATA_QUALITY_MDATAX_HASURA_SERVICE_TOKEN_SECRET
      OTEL_EXPORTER_OTLP_ENDPOINT: $DATA_QUALITY_MDATAX_OTEL_EXPORTER_OTLP_ENDPOINT
      OTEL_SERVICE_NAME: $DATA_QUALITY_MDATAX_OTEL_SERVICE_NAME
      DATABASE_URL: $DATABASE_URL
    extra_hosts:
      - local.hasura.dev:host-gateway
    ports:
      - 5176:8080
