name: Sync Wiki to Repo

on:
  gollum:
  workflow_dispatch:

jobs:
  sync-wiki:
    if: ${{ github.repository == 'hasura/community' }}
    runs-on: ubuntu-latest

    steps:
      - name: Checkout main repository
        uses: actions/checkout@v3

      - name: Checkout wiki repository
        uses: actions/checkout@v3
        with:
          repository: ${{ github.repository }}.wiki
          path: .wiki-tmp

      - name: Remove .git directory
        run: rm -rf .wiki-tmp/.git

      - name: Sync wiki to main repo
        run: |
          rm -rf .wiki
          mv .wiki-tmp .wiki

      - name: Commit and push changes
        run: |
          git config --global user.name "GitHub Action"
          git config --global user.email "action@github.com"
          git add .wiki
          git commit -m "Sync wiki to main repo"
          git push

